spring:
  application:
      name: project-api
       
## Hibernate Properties
# The SQL dialect makes Hibernate generate better SQL for the chosen database
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    # Hibernate ddl auto (create, create-drop, validate, update)
    hibernate:
      ddl-auto: update
      show-sql: true
  datasource:
    url: jdbc:mysql://{YOUR_MSQL_SERVER}:3306/{DATABASE NAME}?useSSL=false
    username: { YOUR_MYSQL_ID }
    password: { YOUR_MYSQL_PASSWORD }
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 2

server:
  port: 8080

application-description: 'project-api'
application-version: '0.0.1'
# swagger-ui custom path
springdoc:
  version: '@springdoc.version@'
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /v3/api-docs
